// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn6jqvI-5XvPTcstC28LRLmBAzeN938Is',
    appId: '1:511284616889:web:eaab13ad5a4bcabbfd4568',
    messagingSenderId: '511284616889',
    projectId: 'tiktokclone-ae9cb',
    authDomain: 'tiktokclone-ae9cb.firebaseapp.com',
    storageBucket: 'tiktokclone-ae9cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBank7rhAST02_xs6sKCTKlU5tfgTJotl4',
    appId: '1:511284616889:android:69b832832aff4c01fd4568',
    messagingSenderId: '511284616889',
    projectId: 'tiktokclone-ae9cb',
    storageBucket: 'tiktokclone-ae9cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5jRXVY0t1jjYw_wF70ucT00-V3jhkqDQ',
    appId: '1:511284616889:ios:3a91e47478ac62fafd4568',
    messagingSenderId: '511284616889',
    projectId: 'tiktokclone-ae9cb',
    storageBucket: 'tiktokclone-ae9cb.appspot.com',
    iosClientId: '511284616889-uilfose5td75k3bodtgfcgm61gk5qk2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokappclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5jRXVY0t1jjYw_wF70ucT00-V3jhkqDQ',
    appId: '1:511284616889:ios:3a91e47478ac62fafd4568',
    messagingSenderId: '511284616889',
    projectId: 'tiktokclone-ae9cb',
    storageBucket: 'tiktokclone-ae9cb.appspot.com',
    iosClientId: '511284616889-uilfose5td75k3bodtgfcgm61gk5qk2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokappclone',
  );
}
